version: '3.8'

services:
  devops-portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: devops-portfolio-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - portfolio-dev-network
    stdin_open: true
    tty: true

networks:
  portfolio-dev-network:
    driver: bridge
