version: '3.8'

services:
  devops-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-portfolio
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.localhost`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

  # Optional: Add a reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - devops-portfolio
    networks:
      - portfolio-network
    profiles:
      - production

networks:
  portfolio-network:
    driver: bridge

volumes:
  ssl-certs:
    driver: local
